name: zeytinx
description: ZeytinX is a comprehensive local data management and module library prepared to develop large-scale applications (social media, e-commerce, forum, messaging, community, etc.) using the zeytin_local_storage infrastructure.
version: 1.3.3
repository: https://github.com/JeaFrid/ZeytinX
homepage: https://github.com/JeaFrid/ZeytinX
issue_tracker: https://github.com/JeaFrid/ZeytinX/issues

environment:
  sdk: ^3.0.0

dependencies:
  uuid: ^4.5.3
  zeytin_local_storage: ^1.2.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
